### ISSUE TITLE
Update to latest eclipse release

### ISSUE THREAD

**Issue by graemeg** [daemonblade/freebsd-eclipse#6]
Is there any chance updating to latest eclipse release, which is now 4.23 (and the latest FreeBSD port is 4.16).

**Comment by daemonblade** [comment]
The critical bugs stopping the release has now been resolved, and the port will be bumped to 4.21, before another update to 4.24 next month
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=264400
